export const EMAIL_AUTH_SIGNUP_REQUEST = "EMAIL_AUTH/SIGNUP/REQUEST";
export const EMAIL_AUTH_SIGNUP_SUCCESS = "EMAIL_AUTH/SIGNUP/SUCCESS";
export const EMAIL_AUTH_SIGNUP_ERROR = "EMAIL_AUTH/SIGNUP/ERROR";

export const EMAIL_AUTH_LOGIN_REQUEST = "EMAIL_AUTH/LOGIN/REQUEST";
export const EMAIL_AUTH_LOGIN_SUCCESS = "EMAIL_AUTH/LOGIN/SUCCESS";
export const EMAIL_AUTH_LOGIN_ERROR = "EMAIL_AUTH/LOGIN/ERROR";

// does not follow the patern REQUERST/SUCCESS/ERROR since it is syncronus action
export const EMAIL_AUTH_LOGOUT = "EMAIL_AUTH/LOGOUT";

export const EMAIL_AUTH_PASSWORD_RECOVER_REQUEST = "EMAIL_AUTH/PASSORD_RECOVER/REQUEST";
export const EMAIL_AUTH_PASSWORD_RECOVER_SUCCESS = "EMAIL_AUTH/PASSORD_RECOVER/SUCCESS";
export const EMAIL_AUTH_PASSWORD_RECOVER_ERROR = "EMAIL_AUTH/PASSORD_RECOVER/ERROR";
