name: create-github-release

on:
  workflow_dispatch:
  repository_dispatch:
    types:
      - create-github-release

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      working-directory: ./django-scaffold
    environment: production
    steps:
      - name: Repo Clone
        id: repo-clone 
        run: |
          git clone https://${{ secrets.GIT_TOKEN }}@github.com/crowdbotics/django-scaffold.git

      - name: Clone Reusable Actions Repo
        id: reusable-actions-clone
        run: |
          git clone -b master https://${{ secrets.GIT_TOKEN }}@github.com/crowdbotics/github-actions.git
      
      - name: Checkout branch
        id: checkout
        working-directory: ${{ env.working-directory }}
        run: |
          if [ ${{ github.event.client_payload.release_branch }} == "master" ]; then
            echo "branch: ${{ github.event.client_payload.release_branch }}"
            git checkout ${{ github.event.client_payload.release_branch }}
          else
            echo "manual deployment"
            echo "branch: ${GITHUB_REF_NAME}"
            git checkout ${GITHUB_REF_NAME}
          fi
      
      - name: Run Release Workflow
        uses: ./github-actions/create-github-release
        id: release
        with:
          working-directory: ${{ env.working-directory }}
          GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          release_branch: ${{ github.event.client_payload.release_branch }}

      - name: Azure login
        uses: azure/login@v2.1.1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: "v0.0.25"

      - name: Get K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AZURE_CLUSTER_NAME }}
          admin: "false"
          use-kubelogin: "true"

      - name: Update DJANGO_SCAFFOLD_REPO_BRANCH Environment Variable
        id: update-env-var
        uses: ./github-actions/set-azure-env-var
        with:
          resource_group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster_name: ${{ secrets.AZURE_CLUSTER_NAME }}
          app_name: crowdbotics-app
          app_namespace: cb-core
          env_var: DJANGO_SCAFFOLD_REPO_BRANCH
          env_value: ${{ steps.release.outputs.tag_version }}
          token: ${{ secrets.GIT_TOKEN }}
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: act10ns/slack@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
