name: test-scaffold-updates

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Run a simple test
        run: echo "This is a test that always succeeds!"

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: List the contents of the current directory
        run: ls

      - name: Remove existing tmp_cookiecutter_output directory if it exists
        run: |
          rm -rf tmp_cookiecutter_output

      - name: Scaffold a new project
        run: |
          cookiecutter https://github.com/crowdbotics/django-scaffold \
          --checkout test-PI-264 \
          --no-input --output-dir tmp_cookiecutter_output_2 \
          project_name="Test project" \
          project_generated_name="test-project" \
          owner_email="juan@cm.com "

      - name: List the scaffolded project
        run: | 
          ls tmp_cookiecutter_output_2

      - name: Check the scaffolded project
        run: |
          cd tmp_cookiecutter_output_2
          cd testproject
          python manage.py test