name: test-scaffold-updates

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Run a simple test
        run: echo "This is a test that always succeeds!"

      - name: Install Cookiecutter
        run: pip install cookiecutter

      - name: List the contents of the current directory
        run: ls

      - name: Remove existing tmp_cookiecutter_output directory if it exists
        run: |
          rm -rf tmp_cookiecutter_output

      - name: Scaffold a new project
        run: |
          cookiecutter https://github.com/crowdbotics/django-scaffold --checkout test-PI-264 --output-dir tmp_cookiecutter_output_2

      - name: List the scaffolded project
        run: | 
          ls tmp_cookiecutter_output_2

      - name: Check the scaffolded project
        run: |
          cd my-new-project
          python manage.py test